# Generated by Django 2.2.1 on 2019-06-04 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comment_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='slug',
        ),
    ]
